import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { gql } from "@ts-gql/tag";
import { useQuery } from "@ts-gql/apollo";

const query = gql`
  query HomePage {
    users {
      id
      name
    }
  }
` as import("../__generated__/ts-gql/HomePage").type;

const Home: NextPage = () => {
  const { data, error, ...rest } = useQuery(query);

  console.log({ data, error, rest });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>An app for generating 40k cards</h1>
        <div>loading: {rest.loading.toString()}</div>
      </main>
    </div>
  );
};

export default Home;
