import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { gql } from "@ts-gql/tag/no-transform";
import { useQuery } from "@ts-gql/apollo";

const query = gql`
  query HomePage {
    armyLists {
      name
      id
    }
  }
` as import("../__generated__/ts-gql/HomePage").type;

const Home: NextPage = () => {
  const { data, error, loading } = useQuery(query);

  if (loading) {
    return <div>Loading</div>;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>An app for generating 40k cards</h1>
        <ul>
          {data?.armyLists?.map(({ name, id }) => (
            <li key={name}>
              <Link href={`/army/${id}`}>{name}</Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
